name: Deploy Cloud Function (Gen 2)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gcp/cloud-functions/TEMPLATE--etl-live-1-extract/**'

jobs:
  deploy-gcp-cloud-function:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_CREDENTIALS_JSON }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_CREDENTIALS_JSON }}

      - name: Deploy Cloud Function (Gen 2)
        run: |
          gcloud functions deploy TEMPLATE--etl-live-1-extract \
            --gen2 \
            --region us-east1 \
            --runtime nodejs18 \
            --source gcp/cloud-functions/TEMPLATE--etl-live-1-extract \
            --entry-point extract \
            --memory 8192MB \
            --timeout 540s \
            --trigger-event google.cloud.pubsub.topic.v1.messagePublished \
            --trigger-resource --trigger-resource projects/${{ secrets.GCP_PROJECT_ID }}/topics/test
            --service-account test-648@bits-sandbox-450720.iam.gserviceaccount.com # Ensure this SA has the correct permissions.
